### ISSUE TITLE
Package firefox is not available

### ISSUE THREAD

**Issue by LiohMoeller** [rtts/debian#3]
```Install Firefox...
  debian-ansible.domain.example failed | msg: No package matching 'firefox' is available
```
Package name on default debian installs would be firefox-esr

**Comment by LiohMoeller** [comment]
rescue works though:

```
  rescue:
    - name: Install Firefox ESR instead
      become: true
      apt:
        state: present
        name:
          - firefox-esr
```
Maybe just switch?
